In [1]:
import numpy as np

In [6]:
arr = np.array([[1, 2, 3],[6,7,8]])

print(arr)

[[1 2 3]
 [6 7 8]]


In [8]:
arrList=[1,2,3]
print(arrList*2)

[1, 2, 3, 1, 2, 3]


In [9]:
arrList=np.array([1,2,3])
print(arrList*2)

[2 4 6]


## building array

In [20]:
zeros=np.zeros((2,3))
print("zeros:",zeros)

ones=np.ones((2,3))
print("ones:",ones)

full=np.full((2,3),4)
print("full:",full)

random=np.random.random((2,3))
print("random:",random)

sequence=np.arange(0,10,2)
print("sequence:",sequence)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
full: [[4 4 4]
 [4 4 4]]
random: [[0.17631976 0.79157147 0.10566932]
 [0.52529762 0.9030971  0.00637008]]
sequence: [0 2 4 6 8]


## Tensor

In [21]:
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor:",tensor)

tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Properties of array

In [24]:
arr = np.array([[1, 2],[6,7]])
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("size:",arr.size)
print("dtype:",arr.dtype)

dimension: 2
shape: (2, 2)
size: 4
dtype: int64


# Array reshaping

In [30]:
arr=np.arange(12)
print("orginal array:",arr)
reshape=arr.reshape((3,4))
print("reshape array:",reshape)
flatten=reshape.flatten()
print("flatten array:",flatten)
ravel=reshape.ravel()
print("ravel array:",ravel)

# Transpose
transpose=reshape.T
print("transpose:",transpose)

orginal array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
