## Numpy basic operations


In [3]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:4])
print("With Step",arr[1:8:2])
print("Negative indexing",arr[-3])

Basic Slicing [3 4]
With Step [2 4 6 8]
Negative indexing 8


In [5]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element",arr_2d[2,2])
print("Entire row:",arr_2d[1])
print("Entire col:",arr_2d[:,2])

Specific element 9
Entire row: [4 5 6]
Entire col: [3 6 9]


In [10]:
unsorted=np.array([3,1,4,1,5,9])
print("sorted array",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[2,1],[2,3]])
print("sorted 2d_array",np.sort(arr_2d_unsorted,axis=0))

sorted array [1 1 3 4 5 9]
sorted 2d_array [[2 1]
 [2 1]
 [3 3]]


## Filter

In [11]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print("Even numbers",even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [12]:
mask=numbers>5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## fancy indexing vs np.where()

In [8]:

indices=[0,2,3]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print("Np where",numbers[where_result])

[1 3 4]
(array([5, 6, 7, 8, 9]),)
Np where [ 6  7  8  9 10]


In [13]:
condition_array=np.where(numbers>4,numbers*3,numbers)
print(condition_array)

[ 1  2  3  4 15 18 21 24 27 30]


### Adding and removing data

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6 7]


### array compatibility

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([7,8,9])
print("compatibility shape",a.shape==b.shape)

compatibility shape False


In [ ]:
orginal=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
print("with_new_row",np.vstack((orginal,new_row)))


new_col=np.array([[7],[8]])
print("with_new_col",np.hstack((orginal,new_col)))

with_new_row [[1 2]
 [3 4]
 [5 6]]
with_new_col [[1 2 7]
 [3 4 8]]


In [24]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("Array after deletion",deleted)

Array after deletion [1 2 4 5]
